"""ODIN auto-start manager — installs/removes a Windows-login launcher.

What this does:
  1. Drops a `.vbs` wrapper into `data/launcher/odin_silent.vbs` that runs
     `pythonw.exe main.py` with NO visible console window.
  2. Creates a shortcut at `shell:startup` pointing at that wrapper, so the
     wrapper runs every time the user logs in.
  3. ALSO flips `vesta.start_hidden: true` in config.yaml so the GUI starts
     in tray-only mode rather than popping up on every login.

  Usage:
      python setup_autostart.py enable     # install both
      python setup_autostart.py disable    # remove both
      python setup_autostart.py status     # show current state

Important: this assumes Python is installed with `pythonw.exe` available
(it ships with the standard Python installer). The wrapper finds it via
`sys.executable` and substitutes `python.exe` → `pythonw.exe`.

Why a .vbs wrapper and not a direct shortcut to python.exe? Because a
direct shortcut to pythonw.exe still flashes a brief console window in
some Windows configurations. The .vbs trick uses `Wscript.Shell.Run` with
window-style 0, which is genuinely invisible.

Why not a real Windows Service? Services run as SYSTEM by default and
can't easily access the user's mic, speakers, or interactive desktop —
exactly the things ODIN needs. A login-startup is the right tier.
"""

import os
import sys
import yaml
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LAUNCHER_DIR = ROOT / "data" / "launcher"
VBS_PATH = LAUNCHER_DIR / "odin_silent.vbs"
PYW_WRAPPER_PATH = LAUNCHER_DIR / "odin_boot.pyw"
SHORTCUT_NAME = "ODIN.lnk"
CONFIG_PATH = ROOT / "config.yaml"


def _startup_folder() -> Path:
    """Resolve %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup."""
    appdata = os.environ.get("APPDATA")
    if not appdata:
        raise RuntimeError("APPDATA env var not set — are you on Windows?")
    return Path(appdata) / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"


def _shortcut_path() -> Path:
    return _startup_folder() / SHORTCUT_NAME


def _pythonw_path() -> str:
    """Substitute pythonw.exe for python.exe in sys.executable. pythonw
    is the windowless variant — it runs without spawning a console."""
    p = sys.executable
    if p.endswith("python.exe"):
        candidate = p[:-len("python.exe")] + "pythonw.exe"
        if os.path.exists(candidate):
            return candidate
    if p.endswith("pythonw.exe"):
        return p
    raise RuntimeError(
        f"Couldn't find pythonw.exe alongside {p}. Reinstall Python with the "
        f"'tcl/tk and IDLE' option which bundles pythonw."
    )


def _write_pyw_wrapper():
    """A tiny Python wrapper that redirects stdout/stderr to a log file and
    then invokes main.boot(). Solves the silent-crash problem: pythonw.exe
    by default discards stdout/stderr, so when ODIN dies during import the
    user sees nothing. With this wrapper, any boot exception (missing dep,
    config error, port conflict) gets a full traceback in launcher.log."""
    LAUNCHER_DIR.mkdir(parents=True, exist_ok=True)
    log_path = ROOT / "data" / "logs" / "launcher.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)

    wrapper = (
        '"""Launcher wrapper (generated by setup_autostart.py). Do not edit —\n'
        're-run `python setup_autostart.py enable` (or setup_app_shortcuts.py\n'
        'install) to regenerate."""\n'
        'import os, sys, traceback, datetime\n'
        '\n'
        f'_ROOT = r"{ROOT}"\n'
        f'_LOG  = r"{log_path}"\n'
        '\n'
        'os.chdir(_ROOT)\n'
        'if _ROOT not in sys.path:\n'
        '    sys.path.insert(0, _ROOT)\n'
        '\n'
        '# Tee stdout/stderr to a log file so boot crashes are visible after\n'
        '# the fact. pythonw.exe normally discards both streams.\n'
        '_logf = open(_LOG, "a", encoding="utf-8", buffering=1)\n'
        '_logf.write(f"\\n===== ODIN boot {datetime.datetime.now().isoformat(timespec=\'seconds\')} =====\\n")\n'
        'sys.stdout = _logf\n'
        'sys.stderr = _logf\n'
        '\n'
        'try:\n'
        '    import main\n'
        '    main.boot()\n'
        'except SystemExit:\n'
        '    raise\n'
        'except BaseException:\n'
        '    traceback.print_exc(file=_logf)\n'
        '    _logf.flush()\n'
        '    raise\n'
    )
    PYW_WRAPPER_PATH.write_text(wrapper, encoding="utf-8")
    return PYW_WRAPPER_PATH


def _write_vbs():
    LAUNCHER_DIR.mkdir(parents=True, exist_ok=True)
    pyw = _pythonw_path()
    wrapper = _write_pyw_wrapper()
    # Simple, robust: pythonw runs the wrapper, the wrapper handles its own
    # logging. No cmd /c, no shell-redirect quoting traps.
    vbs_content = (
        f'Set WshShell = CreateObject("WScript.Shell")\n'
        f'WshShell.CurrentDirectory = "{ROOT}"\n'
        f'WshShell.Run """{pyw}"" ""{wrapper}""", 0, False\n'
    )
    VBS_PATH.write_text(vbs_content, encoding="utf-8")
    return VBS_PATH


def _make_shortcut():
    """Create a .lnk in the user's Startup folder pointing at the .vbs.
    Uses pywin32 if available (cleanest); falls back to a PowerShell
    one-liner if not."""
    target = str(VBS_PATH)
    lnk = _shortcut_path()
    lnk.parent.mkdir(parents=True, exist_ok=True)

    try:
        from win32com.client import Dispatch
        shell = Dispatch("WScript.Shell")
        s = shell.CreateShortcut(str(lnk))
        s.TargetPath = target
        s.WorkingDirectory = str(ROOT)
        s.Description = "ODIN — Omniscient Digital Intelligence Node"
        s.IconLocation = sys.executable + ",0"
        s.Save()
        return lnk
    except ImportError:
        pass

    # Fallback — PowerShell. Slower but no extra deps.
    import subprocess
    ps = (
        f'$ws = New-Object -ComObject WScript.Shell; '
        f'$s = $ws.CreateShortcut("{lnk}"); '
        f'$s.TargetPath = "{target}"; '
        f'$s.WorkingDirectory = "{ROOT}"; '
        f'$s.Description = "ODIN"; '
        f'$s.Save()'
    )
    subprocess.run(["powershell", "-NoProfile", "-Command", ps], check=True)
    return lnk


def _set_start_hidden(value: bool):
    """Flip vesta.start_hidden in config.yaml so the GUI launches in tray."""
    cfg = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8")) or {}
    cfg.setdefault("vesta", {})["start_hidden"] = value
    # Re-dump preserving comments isn't possible with PyYAML stdlib; we accept
    # comment loss only on the vesta block. If you want full preservation,
    # install `ruamel.yaml` and swap the loader.
    CONFIG_PATH.write_text(
        yaml.safe_dump(cfg, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )


def enable():
    print("Installing ODIN autostart…")
    vbs = _write_vbs()
    print(f"  Wrote launcher: {vbs}")
    lnk = _make_shortcut()
    print(f"  Created shortcut: {lnk}")
    _set_start_hidden(True)
    print("  Flipped vesta.start_hidden → true (GUI starts in tray)")
    print()
    print("ODIN will now start automatically at Windows login.")
    print("It runs silently in the system tray. Click the tray icon to open the window.")


def disable():
    print("Removing ODIN autostart…")
    removed_any = False
    lnk = _shortcut_path()
    if lnk.exists():
        lnk.unlink()
        print(f"  Removed shortcut: {lnk}")
        removed_any = True
    if VBS_PATH.exists():
        VBS_PATH.unlink()
        print(f"  Removed launcher: {VBS_PATH}")
        removed_any = True
    if not removed_any:
        print("  Nothing to remove (autostart wasn't installed).")
    _set_start_hidden(False)
    print("  Flipped vesta.start_hidden → false (GUI shows on launch again)")


def status():
    print("ODIN autostart status:")
    print(f"  Launcher .vbs: {'EXISTS' if VBS_PATH.exists() else 'missing'}  ({VBS_PATH})")
    print(f"  Startup .lnk:  {'EXISTS' if _shortcut_path().exists() else 'missing'}  ({_shortcut_path()})")
    try:
        cfg = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8")) or {}
        hidden = cfg.get("vesta", {}).get("start_hidden", False)
        print(f"  start_hidden:  {hidden}")
    except Exception as e:
        print(f"  start_hidden:  (could not read config: {e})")


def main():
    if len(sys.argv) < 2 or sys.argv[1] not in ("enable", "disable", "status"):
        print(__doc__)
        sys.exit(1)
    {
        "enable":  enable,
        "disable": disable,
        "status":  status,
    }[sys.argv[1]]()


if __name__ == "__main__":
    main()
